name: 'template_srv'
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  srv_base:
    git: https://github.com/vgordievskiy/embla_min_version.git

dependency_overrides:
  trestle: ^0.8.0
  dart_jwt: ^0.5.1

dev_dependencies:
  SemplexClientCmn:
    git: https://github.com/vgordievskiy/ClientCommon.git
  grinder: any
  test: any
